import { readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

type SourceFile = {
  path: string
  text: string
  lines: number
}

type PatternInfo = {
  name: string
  status: string
  pattern: RegExp
  note: string
}

type PatternSummary = {
  info: PatternInfo
  count: number
  files: Map<string, number>
}

const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const compilerRoot = join(repoRoot, 'src/compiler')
const outputPath = join(repoRoot, 'docs/compiler-self-hosting-capability-matrix.md')

const patterns: PatternInfo[] = [
  {
    name: 'AnyNode / open AST shapes',
    status: 'rewrite',
    pattern: /\bAnyNode\b/g,
    note: 'Replace hot paths with explicit AST/HIR/IR node shapes before self-hosting.'
  },
  {
    name: 'object/array spread',
    status: 'rewrite or implement',
    pattern: /\.\.\./g,
    note: 'Current C subset does not lower broad spread-heavy object copying.'
  },
  {
    name: 'Object.entries / Object.keys / Object.values',
    status: 'rewrite or implement',
    pattern: /\bObject\.(entries|keys|values)\s*\(/g,
    note: 'Prefer explicit loops over known arrays of records in compiler-core.'
  },
  {
    name: 'Array.from',
    status: 'rewrite or implement',
    pattern: /\bArray\.from\s*\(/g,
    note: 'Usually replaceable with direct array accumulation.'
  },
  {
    name: 'flatMap / map / filter / reduce / sort',
    status: 'rewrite or broaden stdlib',
    pattern: /\.(flatMap|map|filter|reduce|sort)\s*\(/g,
    note: 'Some array methods exist at runtime, but broad generic callback use is not self-hosting-ready.'
  },
  {
    name: 'try / catch',
    status: 'implement or isolate',
    pattern: /\b(try|catch)\b/g,
    note: 'Use only at host adapter boundaries until C exception lowering is planned.'
  },
  {
    name: 'async / await',
    status: 'supported slice, review',
    pattern: /\b(async|await)\b/g,
    note: 'Compiler-core should start in-memory; module graph loading can stay behind host adapters.'
  },
  {
    name: 'RegExp usage',
    status: 'rewrite or implement',
    pattern: /\bRegExp\b|(^|[=(,:\s])\/(?:\\.|[^/\n])+\/[dgimsuvy]*/gm,
    note: 'Lexer, parser helpers and C formatting should avoid regex where a small scanner is clearer.'
  },
  {
    name: 'generic container types',
    status: 'simplify types',
    pattern: /\b(Record|ReadonlyMap|Map|Set)<|ReadonlyArray</g,
    note: 'Self-hosted type surface should prefer explicit aliases and concrete record arrays.'
  }
]

async function main(): Promise<void> {
  const mode = process.argv.includes('--write') ? 'write' : process.argv.includes('--check') ? 'check' : 'print'
  const files = await readSourceFiles(compilerRoot)
  const markdown = renderMatrix(files)

  if (mode === 'write') {
    await writeFile(outputPath, markdown)
    return
  }

  if (mode === 'check') {
    const current = await readFile(outputPath, 'utf8').catch(() => '')

    if (current !== markdown) {
      console.error(`${relative(repoRoot, outputPath)} is stale. Run pnpm run audit:self-hosting -- --write.`)
      process.exitCode = 1
    }
    return
  }

  process.stdout.write(markdown)
}

async function readSourceFiles(root: string): Promise<SourceFile[]> {
  const files: SourceFile[] = []

  await walk(root)

  return files.sort((left, right) => left.path.localeCompare(right.path))

  async function walk(dir: string): Promise<void> {
    const entries = await readdir(dir, {
      withFileTypes: true
    })

    for (const entry of entries) {
      const path = join(dir, entry.name)

      if (entry.isDirectory()) {
        await walk(path)
        continue
      }

      if (!entry.isFile() || !entry.name.endsWith('.ts')) {
        continue
      }

      const text = await readFile(path, 'utf8')

      files.push({
        path: relative(repoRoot, path),
        text,
        lines: text.split('\n').length
      })
    }
  }
}

function renderMatrix(files: SourceFile[]): string {
  const totalLines = files.reduce((sum, file) => sum + file.lines, 0)
  const hostImports = collectHostImports(files)
  const summaries = patterns.map((info) => summarizePattern(info, files))
  const largest = [...files].sort((left, right) => right.lines - left.lines).slice(0, 10)

  const lines: string[] = [
    '# Compiler Self-Hosting Capability Matrix',
    '',
    '<!-- Generated by `node scripts/audit-self-hosting.ts --write`. Do not edit tables by hand. -->',
    '',
    'This matrix makes the self-hosting blockers in `src/compiler` measurable. It',
    'is intentionally an audit artifact, not a failing support matrix: unsupported',
    'features are expected while the compiler is still hosted by Node.',
    '',
    '## Snapshot',
    '',
    `- TypeScript files: ${files.length}`,
    `- TypeScript lines: ${totalLines}`,
    `- Largest file: ${largest[0]?.path ?? '-'} (${largest[0]?.lines ?? 0} lines)`,
    '',
    '## Largest Files',
    '',
    '<!-- prettier-ignore-start -->',
    '| File | Lines |',
    '| --- | ---: |',
    ...largest.map((file) => `| \`${file.path}\` | ${file.lines} |`),
    '<!-- prettier-ignore-end -->',
    '',
    '## Host Node Imports',
    '',
    '<!-- prettier-ignore-start -->',
    '| Module | Files |',
    '| --- | --- |',
    ...[...hostImports.entries()].map(([module, moduleFiles]) => {
      const fileList = [...moduleFiles]
        .sort()
        .map((file) => `\`${file}\``)
        .join('<br>')

      return `| \`${module}\` | ${fileList} |`
    }),
    '<!-- prettier-ignore-end -->',
    '',
    '## Feature Heuristics',
    '',
    '<!-- prettier-ignore-start -->',
    '| Feature | Status | Matches | Hot Files | Note |',
    '| --- | --- | ---: | --- | --- |',
    ...summaries.map((summary) => {
      const hotFiles = [...summary.files.entries()]
        .sort((left, right) => right[1] - left[1])
        .slice(0, 5)
        .map(([file, count]) => `\`${file}\` (${count})`)
        .join('<br>')

      return `| ${summary.info.name} | ${summary.info.status} | ${summary.count} | ${hotFiles || '-'} | ${summary.info.note} |`
    }),
    '<!-- prettier-ignore-end -->',
    '',
    '## Work Queue',
    '',
    '1. Keep the first self-hosted target in-memory and compiler-core only.',
    '2. Put `node:fs/promises`, `node:path`, `node:url` and `node:crypto` host dependencies behind adapters or ccjs stdlib slices.',
    '3. Extract the remaining large C emitter clusters before trying to compile `src/compiler/c/index.ts` with ccjs.',
    '4. Replace new `AnyNode` mutation surfaces with explicit node shapes as code is touched.',
    '5. Rewrite regex-heavy helpers only when a small scanner is simpler than broad RegExp runtime support.'
  ]

  return `${lines.join('\n')}\n`
}

function collectHostImports(files: SourceFile[]): Map<string, Set<string>> {
  const imports = new Map<string, Set<string>>()
  const importPattern = /\bfrom\s+['"](node:[^'"]+)['"]/g

  for (const file of files) {
    for (const match of file.text.matchAll(importPattern)) {
      const module = match[1]
      const moduleFiles = imports.get(module) ?? new Set<string>()

      moduleFiles.add(file.path)
      imports.set(module, moduleFiles)
    }
  }

  return new Map([...imports.entries()].sort(([left], [right]) => left.localeCompare(right)))
}

function summarizePattern(info: PatternInfo, files: SourceFile[]): PatternSummary {
  const summary: PatternSummary = {
    info,
    count: 0,
    files: new Map()
  }

  for (const file of files) {
    const matches = [...file.text.matchAll(info.pattern)].length

    if (matches === 0) {
      continue
    }

    summary.count += matches
    summary.files.set(file.path, matches)
  }

  return summary
}

await main()
